import {COLS,ROWS,EMPTY,GARBAGE,emptyBoard,createSequence,enumerateMoves,heuristicMove,forecastChains,boardToText,dropGarbage,isGameOver} from "./engine.js";
const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const COLORS=["#ed385d","#329cf5","#42d76f","#f5c329","#d8e3ff"];let match=null,token=0;
function player(id){return{id,board:emptyBoard(),score:0,maxChain:0,pending:0,alive:true,canvas:$(`#${id}-board`),mode:$(`#${id}-mode`).value,strategy:$(`#${id}-strategy`).value};}
function draw(p){const c=p.canvas.getContext("2d"),w=p.canvas.width/COLS,h=p.canvas.height/(ROWS-1);c.clearRect(0,0,p.canvas.width,p.canvas.height);const bg=c.createLinearGradient(0,0,0,p.canvas.height);bg.addColorStop(0,"#12205a");bg.addColorStop(1,"#05091e");c.fillStyle=bg;c.fillRect(0,0,p.canvas.width,p.canvas.height);for(let r=1;r<ROWS;r++)for(let col=0;col<COLS;col++){const color=p.board[r][col];if(color===EMPTY)continue;const x=col*w+3,y=(r-1)*h+3,s=w-6;c.fillStyle=COLORS[color];c.shadowColor=COLORS[color];c.shadowBlur=color===GARBAGE?2:9;c.beginPath();c.roundRect(x,y,s,s,s*.42);c.fill();c.shadowBlur=0;if(color===GARBAGE){c.fillStyle="#5e6b8c";c.beginPath();c.arc(x+s*.38,y+s*.46,3,0,7);c.arc(x+s*.62,y+s*.46,3,0,7);c.fill();}else{c.fillStyle="#fff";c.beginPath();c.ellipse(x+s*.4,y+s*.52,4,6,0,0,7);c.ellipse(x+s*.61,y+s*.52,4,6,0,0,7);c.fill();}}}
function update(p){draw(p);$(`#${p.id}-score`).textContent=p.score.toLocaleString();$(`#${p.id}-chain`).textContent=p.maxChain;$(`#${p.id}-garbage`).textContent=p.pending;$(`#${p.id}-status`).textContent=p.alive?"ACTIVE":"DOWN";}
function safe(moves){return moves.map(({resultBoard,steps,cells,...m})=>m)}
async function choose(p,pair,next,index){const moves=enumerateMoves(p.board,pair);if(!moves.length)return null;if(p.strategy==="chain"){const f=forecastChains(moves,match.sequence.slice(index+1,index+9));for(const m of moves)Object.assign(m,f.get(m.id));}if(p.mode==="heuristic")return p.strategy==="chain"?[...moves].sort((a,b)=>b.forecastValue-a.forecastValue)[0]:heuristicMove(moves,p.strategy);const finalists=p.strategy==="chain"?[...moves].sort((a,b)=>b.forecastValue-a.forecastValue).slice(0,2):moves;const response=await fetch("/api/decide",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({board:boardToText(p.board),pair:"RGBY"[pair[0]]+"RGBY"[pair[1]],next:"RGBY"[next[0]]+"RGBY"[next[1]],candidates:safe(finalists),mode:p.mode,strategy:p.strategy})});const data=await response.json();if(!response.ok)throw new Error(data.error);p.lastDecision=data;return moves.find(m=>m.id===data.moveId)||finalists[0];}
function offset(a,b){let p1Attack=Math.floor(a.move.score/70),p2Attack=Math.floor(b.move.score/70);const old1=a.player.pending,old2=b.player.pending,c1=Math.min(p1Attack,old1),c2=Math.min(p2Attack,old2);p1Attack-=c1;p2Attack-=c2;let remain1=old1-c1,remain2=old2-c2;const clash=Math.min(p1Attack,p2Attack);p1Attack-=clash;p2Attack-=clash;const incoming1=p2Attack,incoming2=p1Attack;return{remain1,remain2,incoming1,incoming2,attack1:Math.floor(a.move.score/70),attack2:Math.floor(b.move.score/70)};}
function landPending(p,count,seed){if(!count)return 0;const amount=Math.min(30,count),result=dropGarbage(p.board,amount,seed);p.board=result.board;p.alive=!result.overflow&&!isGameOver(p.board);return count-amount;}
async function round(run){const {p1,p2}=match,index=match.round,pair=match.sequence[index],next=match.sequence[index+1];$("#round").textContent=`ROUND ${index+1}`;const [m1,m2]=await Promise.all([choose(p1,pair,next,index),choose(p2,pair,next,index)]);if(run!==token)return;if(!m1||!m2){p1.alive=!!m1;p2.alive=!!m2;update(p1);update(p2);return finish();}p1.board=m1.resultBoard;p2.board=m2.resultBoard;p1.score+=m1.score;p2.score+=m2.score;p1.maxChain=Math.max(p1.maxChain,m1.chains);p2.maxChain=Math.max(p2.maxChain,m2.chains);const combat=offset({player:p1,move:m1},{player:p2,move:m2});const carry1=landPending(p1,combat.remain1,match.seed+index*2),carry2=landPending(p2,combat.remain2,match.seed+index*2+1);p1.pending=carry1+combat.incoming1;p2.pending=carry2+combat.incoming2;$(`#p1-decision`).textContent=`${m1.label} / ${m1.chains?m1.chains+"連鎖":"構築"}`;$(`#p2-decision`).textContent=`${m2.label} / ${m2.chains?m2.chains+"連鎖":"構築"}`;$("#attack").textContent=`1P ${combat.attack1}個 →　相殺　← ${combat.attack2}個 2P`;$("#log").insertAdjacentHTML("afterbegin",`<div class="trace-row"><b>${index+1}</b><span>1P ${m1.label} / ${m1.chains}連鎖</span><span class="attack">+${combat.attack1}</span><span>2P ${m2.label} / ${m2.chains}連鎖</span><span class="attack">+${combat.attack2}</span></div>`);match.round++;update(p1);update(p2);if(!p1.alive||!p2.alive)return finish();}
function finish(){match.running=false;const winner=match.p1.alive&&!match.p2.alive?"1P WIN":match.p2.alive&&!match.p1.alive?"2P WIN":"DRAW";$("#result").innerHTML=`<div>${winner}<small style="display:block;font-size:14px;color:#9fb0d8">${match.round} ROUNDS</small></div>`;$("#result").classList.remove("hidden");}
async function loop(run){while(match.running&&run===token){if(match.paused){await sleep(100);continue}try{await round(run)}catch(e){match.running=false;$("#result").textContent=e.message;$("#result").classList.remove("hidden");break}await sleep(550)}}
function start(){token++;const seed=Number($("#seed").value)||4242;match={seed,sequence:createSequence(seed),round:0,p1:player("p1"),p2:player("p2"),running:true,paused:false};$("#result").classList.add("hidden");$("#log").innerHTML="";update(match.p1);update(match.p2);loop(token)}
$("#start").addEventListener("click",start);$("#pause").addEventListener("click",()=>{if(!match)return;match.paused=!match.paused;$("#pause").textContent=match.paused?"RESUME":"PAUSE"});draw(player("p1"));draw(player("p2"));
